assigness: []
harvest_options:
  path: s3://ooi-data
  refresh: false
  test: false
instrument: CE06ISSM-RID16-02-FLORTD000
stream:
  method: telemetered
  name: flort_sample
workflow_config:
  schedule: 0 0 * * *
